# Generated by Django 4.1.7 on 2023-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['created_date']},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_date'], name='blog_like_created_c82e68_idx'),
        ),
    ]
