# Generated by Django 4.1.7 on 2023-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_created_79f39f_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='blog_like_created_c82e68_idx',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='blog_commen_created_0e6ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['-created_date'], name='blog_like_created_4327d8_idx'),
        ),
    ]
